### ISSUE TITLE
fit_mpm failing due to issue with select()

### ISSUE THREAD

**Issue by camrinbraun** [ianjonsen/foieGras#13] opened 2020-03-06 04:44 UTC
**Describe the bug**
Issue running jmpm model in `fit_mpm`. In the following, plocs is a data frame with 10 unique IDs. You can see the function pushes a weird error about how it expected to get only 1 value for model convergence instead of 10 (which is obviously not right because we expect 10, 1 for each unique ID).

```
mpm_fit <- foieGras::fit_mpm(plocs[,c('id','date','lon','lat')], model = 'jmpm')

fitting mpm...
Error: Column `converged` must be length 1 (the group size), not 10
```

**Potential solution**
I went into the `fit_mpm` code and changed the two instances of `select()` from dplyr to actually specify `dplyr::select()` and now the function works as expected. I've had other issues like this with some of the `dplyr` functions lately as if other functions (maybe in `tidyverse`?) are over-riding dplyr functions by the same name.

**Comment by ianjonsen** [comment] 2020-03-09 11:55
I can't reproduce this error using the example data `fssm` in v 0.4.0 (CRAN) or GitHub 0.4.01 (master) and 0.4.01-2 (staging):

```
data(fssm)
dmp <- grab(fssm, "predicted", as_sf=FALSE)
dmp <- dmp[, c("id", "date", "lon", "lat")]
fmp1 <- fit_mpm(dmp, model = "jmpm")
fmp2 <- fit_mpm(dmp, model = "mpm")
```

Not sure which version you're using, but try re-install. If error persists then try re-install of `tidyverse` or at least `dplyr` - might be a corrupt `namespace` issue?

Only other issue is that using `model = 'jmpm'` shouldn't result in 10 convergence results, it should result in 1. using `model = 'mpm'` should result in 10!

**Comment by ianjonsen** [comment] 2020-03-11 15:18
by any chance was `plocs` a `tibble` grouped by `id`? I've just had the same error but only when input is a grouped `tibble`.

**Comment by ianjonsen** [comment] 2020-03-12 15:32
pushed a fix to `foieGras@staging` for cases where input data is a `grouped_df`, fit_mpm now handles grouped and ungrouped input data appropriately based on whether `model = "jmpm"` or `model = "mpm"`

**Comment by ianjonsen** [comment] 2020-03-16 12:30
going to close this issue if there are no other related problems

**Closed** 2020-03-17 11:31 UTC
