### ISSUE TITLE
Installation fails on Ubuntu

### ISSUE THREAD

**Issue by camrinbraun** [ianjonsen/foieGras#10] opened 2019-11-09 00:15 UTC
I'm unable to install the package from CRAN or Github on Ubuntu but works fine on Mac OS. I'm using the recommended install code and have all updated dependencies and suggests.

```
install.packages('foieGras')
## OR
remotes::install_github("ianjonsen/foieGras", dependencies = c("Imports","LinkingTo","Suggests"))
```
The process seems to hang during the installation when the following occurs:
```
...
/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:960:8: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(2) double}’ [-Wignored-attributes]
```

```
> sessionInfo() 
R version 3.6.0 (2019-04-26) 
Platform: x86_64-pc-linux-gnu (64-bit) 
Running under: Ubuntu 18.04.2 LTS  
Matrix products: default BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so  
locale:  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8      [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C               [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C     

attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base      

 loaded via a namespace (and not attached):  [1] ps_1.3.0          prettyunits_1.0.2 withr_2.1.2       crayon_1.3.4      rprojroot_1.3-2    [6] assertthat_0.2.1  R6_2.4.0          backports_1.1.5   magrittr_1.5      rlang_0.4.1       [11] cli_1.1.0         curl_4.2          remotes_2.1.0     rstudioapi_0.10   callr_3.3.2       [16] tools_3.6.0       compiler_3.6.0    processx_3.4.1    pkgbuild_1.0.6
```

**Comment by ianjonsen** [comment] 2019-11-09 11:09
I'm not able to test on Ubuntu 18.04 via travis-ci or rhub (both are stuck on the 16.04 LTS distro). Superficially, this looks like an issue with RCppEigen. What versions of RCppEigen and TMB are you running?

**Comment by camrinbraun** [comment] 2019-11-13 17:57
> sessionInfo() 
R version 3.6.0 (2019-04-26) 
Platform: x86_64-pc-linux-gnu (64-bit) 
Running under: Ubuntu 18.04.2 LTS  
Matrix products: default 
BLAS:   
/usr/lib/x86_64-linux-gnu/openblas/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so  
locale:  
[1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8      [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C               [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C     
attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] TMB_1.7.15          RcppEigen_0.3.3.5.0  
loaded via a namespace (and not attached): [1] compiler_3.6.0  Matrix_1.2-17   tools_3.6.0     Rcpp_1.0.1      grid_3.6.0      lattice_0.20-38

The error prints a BUNCH of stuff that looks like:
>/home/rstudio/R/x86_64-pc-linux-gnu-library/3.6/TMB/include/atomic_math.hpp:426:1:   required from ‘void atomic::matmul(const CppAD::vector<Type>&, CppAD::vector<Type>&) [with Double = double]’
/home/rstudio/R/x86_64-pc-linux-gnu-library/3.6/TMB/include/atomic_math.hpp:426:1:   required from ‘bool atomic::atomicmatmul<Type>::forward(size_t, size_t, const CppAD::vector<bool>&, CppAD::vector<bool>&, const CppAD::vector<Type>&, CppAD::vector<Type>&) [with Type = double; size_t = long unsigned int]’
foieGras.cpp:21:1:   required from here
/usr/local/lib/R/site-library/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:960:8: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(2) double}’ [-Wignored-attributes] 


This works on my mac using `install.packages('foieGras')`.

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6
Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] foieGras_0.4.01     RcppEigen_0.3.3.5.0
loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         lubridate_1.7.4    lattice_0.20-38    tidyr_1.0.0        listenv_0.7.0      prettyunits_1.0.2 
 [7] class_7.3-14       ps_1.3.0           utf8_1.1.4         assertthat_0.2.1   zeallot_0.1.0      rprojroot_1.3-2   
[13] digest_0.6.22      R6_2.4.0           backports_1.1.5    e1071_1.7-2        ggplot2_3.2.1      pillar_1.4.2      
[19] rlang_0.4.1        lazyeval_0.2.2     curl_3.3           rstudioapi_0.9.0   furrr_0.1.0        callr_3.3.2       
[25] Matrix_1.2-15      desc_1.2.0         devtools_2.2.1     stringr_1.4.0      TMB_1.7.15         munsell_0.5.0     
[31] compiler_3.5.2     argosfilter_0.63   pkgconfig_2.0.3    pkgbuild_1.0.6     globals_0.12.4     tidyselect_0.2.5  
[37] tibble_2.1.3       gridExtra_2.3      codetools_0.2-15   fansi_0.4.0        future_1.14.0      crayon_1.3.4      
[43] dplyr_0.8.3        withr_2.1.2        sf_0.8-0           grid_3.5.2         gtable_0.3.0       lifecycle_0.1.0   
[49] DBI_1.0.0          magrittr_1.5       units_0.6-5        scales_1.0.0       KernSmooth_2.23-15 cli_1.1.0         
[55] stringi_1.4.3      fs_1.3.1           remotes_2.1.0      testthat_2.3.0     ellipsis_0.3.0     vctrs_0.2.0       
[61] tools_3.5.2        glue_1.3.1         purrr_0.3.3        processx_3.4.1     pkgload_1.0.2      parallel_3.5.2    
[67] colorspace_1.4-1   sessioninfo_1.1.1  classInt_0.4-2     memoise_1.1.0      usethis_1.5.1

**Comment by ianjonsen** [comment] 2019-11-14 03:28
Ok, nothing unusual with the pkg versions. The RCppEigen msgs are warnings that can't easily be silenced. What does your ~/.R/Makevars file look like?

I'll try to get a local install of ubuntu 18.04 running so I can hopefully reproduce this

**Comment by ianjonsen** [comment] 2019-11-18 03:29
I've tested the install on a fresh ubuntu 18.04 instances and can confirm that a lot of compiler warnings are generated but they're just warnings. It takes a while (maybe 2-5 min) but eventually the compiler finishes and the package builds:

```
foieGras.cpp:21:1:   required from here
/homevol/rstudio/R/x86_64-pc-linux-gnu-library/3.6/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:960:8: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(2) double}’ [-Wignored-attributes]
(cd TMB; /usr/lib/R/bin/Rscript --no-save --no-restore compile.R)
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o foieGras.so foieGras.o -L/usr/lib/R/lib -lR
installing to /homevol/rstudio/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-foieGras/00new/foieGras/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (foieGras)
```

**Comment by camrinbraun** [comment] 2019-11-18 15:16
```sessionInfo()```?

**Comment by ianjonsen** [comment] 2019-11-18 20:25
```sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] ps_1.3.0          prettyunits_1.0.2 withr_2.1.2       crayon_1.3.4
 [5] rprojroot_1.3-2   assertthat_0.2.1  R6_2.4.1          backports_1.1.5
 [9] magrittr_1.5      cli_1.1.0         curl_4.2          remotes_2.1.0
[13] callr_3.3.2       tools_3.6.1       compiler_3.6.1    processx_3.4.1
[17] pkgbuild_1.0.5```

**Comment by camrinbraun** [comment] 2019-12-08 20:14
I tried the CRAN and GitHub install on both Ubuntu 18.04.2 and 18.04.3 with matching versions of `Rcpp` (1.0.3) and `TMB` (1.7.15) to your install. I'm wondering if this issue might be related to running RStudio server on Ubuntu in an AWS EC2 instance. I'm running an RStudio server install from [here](http://www.louisaslett.com/RStudio_AMI/).

**Comment by camrinbraun** [comment] 2020-01-25 19:29
Not sure what has changed since I had this issue but the install from Github is working now.

```
devtools::install_github('ianjonsen/foieGras')
```

```
> sessionInfo() 
R version 3.6.0 (2019-04-26) 
Platform: x86_64-pc-linux-gnu (64-bit) 
Running under: Ubuntu 18.04.2 LTS  

Matrix products: default 
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so  

locale:  
[1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8      [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C               [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C     

attached base packages: 
[1] grid      stats     graphics  grDevices utils     datasets  methods   base       

other attached packages:  
[1] foieGras_0.4.01       tags2etuff_0.0.0.9000 analyzePSAT_0.1.0     rgdal_1.4-4            
[5] gridExtra_2.3         adehabitatLT_0.3.23   CircStats_0.2-6       boot_1.3-20            
[9] MASS_7.3-51.1         adehabitatMA_0.3.13   ade4_1.7-13           raster_2.9-5          
[13] sp_1.3-2              plyr_1.8.4            drake_7.4.0           tidyr_1.0.2           
[17] dplyr_0.8.3           ggplot2_3.2.1         lubridate_1.7.4       fields_10.0           
[21] maps_3.3.0            spam_2.5-1            dotCall64_1.0-0       pracma_2.2.5          
[25] Matrix_1.2-17         oce_1.1-1             gsw_1.0-5             testthat_2.1.1         

loaded via a namespace (and not attached):  
[1] fs_1.3.0           sf_0.8-0           usethis_1.5.0      devtools_2.0.2     RColorBrewer_1.1-2  
[6] rprojroot_1.3-2    tools_3.6.0        TMB_1.7.16         backports_1.1.5    R6_2.4.1          
[11] KernSmooth_2.23-15 DBI_1.1.0          lazyeval_0.2.2     colorspace_1.4-1   withr_2.1.2        
[16] tidyselect_0.2.5   prettyunits_1.0.2  processx_3.3.0     curl_3.3           compiler_3.6.0     
[21] cli_1.1.0          desc_1.2.0         scales_1.0.0       classInt_0.4-2     callr_3.2.0        
[26] argosfilter_0.63   stringr_1.4.0      digest_0.6.23      pkgconfig_2.0.3    sessioninfo_1.1.1  
[31] plotrix_3.7-6      rlang_0.4.3        rstudioapi_0.10    magrittr_1.5       Rcpp_1.0.3         
[36] munsell_0.5.0      lifecycle_0.1.0    furrr_0.1.0        stringi_1.4.3      storr_1.2.1        
[41] pkgbuild_1.0.3     parallel_3.6.0     listenv_0.8.0      crayon_1.3.4       lattice_0.20-38    
[46] zeallot_0.1.0      ps_1.3.0           pillar_1.4.3       igraph_1.2.4.1     base64url_1.4      
[51] codetools_0.2-16   pkgload_1.0.2      glue_1.3.1         remotes_2.0.4      vctrs_0.2.2        
[56] gtable_0.3.0       purrr_0.3.3        future_1.16.0      assertthat_0.2.1   e1071_1.7-3        
[61] class_7.3-15       tibble_2.1.3       memoise_1.1.0      units_0.6-5        globals_0.12.5

```

**Comment by ianjonsen** [comment] 2020-01-30 23:12
glad to hear that, though I haven't pushed any updates since late-November so it's a mystery to me as well.

**Comment by ianjonsen** [comment] 2020-03-03 12:31
going to close this issue if you haven't had additional install problems since

**Comment by camrinbraun** [comment] 2020-03-03 15:03
All good.

**Closed** 2020-03-04 11:56 UTC
